// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"context"
)

type Querier interface {
	GetUserProfileByClerkUserID(ctx context.Context, clerkUserID string) (UserProfile, error)
	UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
