// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profiles.sql

package dbsqlc

import (
	"context"
)

const getUserProfileByClerkUserID = `-- name: GetUserProfileByClerkUserID :one
SELECT
    id,
    clerk_user_id,
    email,
    display_name,
    role,
    created_at,
    updated_at
FROM user_profiles
WHERE clerk_user_id = $1
LIMIT 1
`

func (q *Queries) GetUserProfileByClerkUserID(ctx context.Context, clerkUserID string) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByClerkUserID, clerkUserID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (
    clerk_user_id,
    email,
    display_name,
    role
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (clerk_user_id) DO UPDATE
SET
    email = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    role = EXCLUDED.role,
    updated_at = NOW()
RETURNING
    id,
    clerk_user_id,
    email,
    display_name,
    role,
    created_at,
    updated_at
`

type UpsertUserProfileParams struct {
	ClerkUserID string
	Email       string
	DisplayName string
	Role        string
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.ClerkUserID,
		arg.Email,
		arg.DisplayName,
		arg.Role,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
